name: .NET Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: cd .\WPFTesting\ && dotnet restore

    - name: Build the project
      run: cd .\WPFTesting\ && dotnet build --configuration Release

    - name: Run tests
      run: cd .\WPFTesting\ && dotnet test --configuration Release --no-build --verbosity normal
